### ISSUE TITLE
deleteInstance ?

### ISSUE THREAD

**Issue by markakeller42t** [vidanov/lambda-nodejs-lightsail-backup#14]
Why is line 167 Lightsail.deleteInstance? Shouldnt it be Lightsail.deleteInstanceSnapshot to delete the snapshot and not the instance. I understand the params contents at this point do not contain the instance name, they contain the instance snapshot name but this looked strange to me.

**Comment by vidanov** [comment]
Thank you for pointing this! Corrected. It should be  Lightsail.deleteInstanceSnapshot indeed.

**Comment by markakeller42t** [comment]
Happy to help. Thanks for the project. It is very helpful.
