### ISSUE TITLE
Instance & region naming

### ISSUE THREAD

**Issue by fallingrock** [vidanov/lambda-nodejs-lightsail-backup#17]
I gotta say, your instructions are very good and easy to follow.

With one exception :)

The instance naming in the instructions:

> {name: "Plesk_Hosting_Stack_on_Ubuntu-1GB-Frankfurt-1", region: "eu-central-1", label: "Bunny1"}
> ];

Doesn't correspond to what's in the script.

> const instanceName = "LAMP_Stack-2GB-Frankfurt-1"
> AWS.config.update({ region: 'eu-central-1' });

**Comment by fallingrock** [comment]
OK, I gather the instance naming content in the readme was for an update that had to be rolled back.

**Comment by vidanov** [comment]
Thank you! Corrected the README file.
