### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined at Response.

### ISSUE THREAD

**Issue by shanhyland** [vidanov/lambda-nodejs-lightsail-backup#19]
Hi,
whenever the function has to delete a Snapshot I run into an error:
TypeError: Cannot read property 'name' of undefined at Response.<anonymous> (/var/task/index.js:130:68)
my line 130 is
else console.log('Deleted ' + data.instanceSnapshots[i].name)

I'm pretty sure it's due to the fact that once I get the **Callback** from **Lightsail.deleteInstanceSnapshot** call, I'm already "out" of the loop
**for (var i = 0; i < data.instanceSnapshots.length; i++) { // BROWSE THROUGH SNAPSHOTS** 

And now the **i** value is out-of-range from the data.instanceSnapshots[] array, hence the undefined error.

To fix the issue I replaced 
else console.log('Deleted ' + data.instanceSnapshots[i].name)
by
else console.log(\`Deleted ${paramsDelete.instanceSnapshotName}\`);

**Comment by vidanov** [comment]
Thank you! I put it in the code.

**Comment by shanhyland** [comment]
Great!
Thanks

Le lun. 1 avr. 2019 15:15, Alexey Vidanov <notifications@github.com> a
écrit :
