### ISSUE TITLE
Saving multiple instances

### ISSUE THREAD

**Issue by john-falkus** [vidanov/lambda-nodejs-lightsail-backup#20]
in the latest version of the code the ability to save multiple lightsail instances does not seem to be there any more and the code is different from the online tutorial. Whats the best way of saving multiple instances ? (everything else seems to be working fine, thanks for making this available

**Comment by vidanov** [comment]
IMHO the best way to create snapshots for multiple instances is to create a distinct function for every instance you want to backup.
