### ISSUE TITLE
Set to Backup every 4 hours?

### ISSUE THREAD

**Issue by thatobabusi** [vidanov/lambda-nodejs-lightsail-backup#21]
Hi, I want to set the automated backup to every 4hours:
12am,
4am,
8am, 
12pm,
4pm,
8pm etc...

I checked all over and didnt get a clear idea of how to do that. So I modified it to 
```
rate(4 hours)
```

Is this correct?

**Comment by vidanov** [comment]
`rate (4 hours)`
Yes, it is a valid value! Check this doc out:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
