### ISSUE TITLE
Tips for success

### ISSUE THREAD

**Issue by ai3xbe** [vidanov/lambda-nodejs-lightsail-backup#3]
Not so much of an issue as a few things I found missing from the guide.

1. Make sure you change your AWS region as seen in line 16. Mine was eu-west-2 not EU-central
2. Make sure you change the timeout under basic settings. Mine defaulted to 3 seconds and was causing me errors I didn't understand.

**Comment by vidanov** [comment]
Thank you! I adjusted the README according to your suggestions
