### ISSUE TITLE
Multiple instances in same region - snapshot name conflict

### ISSUE THREAD

**Issue by ChadDevOps** [vidanov/lambda-nodejs-lightsail-backup#7]
With the updated script that supports multiple instances, when you have multiple instances in the same region there is a name conflict when the script attempts to create a snapshot.

**Scenario**:

LightsailInstance1 us-east-2 
LightsailInstance2 us-east-2 
LightsailInstance3 us-east-2 

Script creates snapshot for LightsailInstance1 (TAGKW37TAG0)
Script fails to create snapshot for LightsailInstance2 due to naming conflict (TAGKW37TAG0)
Script fails to create snapshot for LightsailInstance3 due to naming conflict (TAGKW37TAG0)

**Resolution**

I resolved it by adding the instance name to the TAG in the newDaySnapshot function.

`instanceSnapshotName: instanceName + 'TAG' + backupDaysNR`

Only tested it last night, so unknown on long term for daily/weekly/monthly snapshots.

**Comment by vidanov** [comment]
Thank you a lot for reporting this issue! I changed it too. Let's test it for sometime.

**Comment by vidanov** [comment]
Yes, it seems to be good now.
